site:
  title: "LeFolio.md"
  description: "Publish a beautiful website in a breeze from the comfort of Obsidian."
  url: "https://lefolio.md"
  basePath: ""

template: showcase

theme:
  preset: ink
  mode: light

home: "Home.md"

analytics:
  google: G-SNRDM00LCC

author:
  name: "LeFolio"
  bio: "Obsidian-friendly site publishing for academics and makers."
  avatar: "Assets/lefolio_logo_min.png"
  links:
    github: "https://github.com/oilandrust/lefolio-academic"

navigation:
  - Templates
  - Getting Started
  - Docs
